name: 🏷️ Авто-добавление метки auto-merge к PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
  workflow_dispatch:

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Проверка и добавление метки
        uses: actions/github-script@v6
        id: add-label
        with:
          script: |
            const label = "auto-merge";

            try {
              // Для workflow_dispatch
              if (!context.payload.pull_request) {
                console.log('Ручной запуск - обработка всех открытых PR');
                const prs = await github.paginate(
                  github.rest.pulls.list,
                  {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    state: "open",
                    per_page: 100,
                  }
                );

                for (const prItem of prs) {
                  await processPr(prItem.number);
                }
                return;
              }

              // Для событий pull_request
              await processPr(context.payload.pull_request.number);

              async function processPr(prNumber) {
                const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                });

                if (currentLabels.some(l => l.name === label)) {
                  console.log(`PR #${prNumber} уже имеет метку '${label}'`);
                  return;
                }

                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: [label],
                });
                console.log(`Добавлена метка '${label}' к PR #${prNumber}`);
              }
            } catch (error) {
              core.setFailed(`Ошибка: ${error.message}`);
            }

      - name: Проверка BOM в файлах
        if: always()
        run: |
          set -eo pipefail
          echo "Проверка файлов на наличие BOM..."
          found_files=$(grep -rl $'\xEF\xBB\xBF' . || true)

          if [ -n "$found_files" ]; then
            echo "Найдены файлы с BOM:"
            echo "$found_files"
            echo "::error::Обнаружены файлы с BOM-маркером!"
            exit 1
          else
            echo "Файлы с BOM не найдены."
          fi
