# Example configuration file for Jarvis
# Values here override defaults defined in Settings
# e.g.
# log_level: DEBUG
# voice_enabled: false

plugin_dir: plugins
intent_model_path: models/intent
recognition_language: ru-RU
tts_language: ru

# Limit network operations to these CIDR ranges
allowed_networks:
  - "10.0.0.0/8"
  - "192.168.0.0/16"

# Modules to load automatically on startup in order of priority.
# Lower values indicate higher priority.
autoload_modules:
  voice_interface: 10
  sql_interface: 50

dynamic_scaler:
  check_interval: 5
  cpu_threshold: 80
  memory_threshold: 80

agent:
  poll_interval: 5.0
  max_task_timeout: 60.0
  max_concurrent_tasks: 10
  enable_metrics: true
  metrics_port: 8000

rabbitmq:
  host: "rabbitmq"
  port: 5672
  queue: "codex_tasks"

security:
  sandbox_enabled: true
  memory_limit_mb: 100
