name: Jarvis Full Auto CI

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main]
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  lint:
    name: "✅ Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff

      - name: Run Black
        run: black . --check

      - name: Run isort
        run: isort . --check-only

      - name: Run Ruff
        run: ruff .

  test:
    name: "🧪 Tests"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --maxfail=3 --disable-warnings

  codex-agent:
    name: "🧠 Auto-Fix with Codex"
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ needs.test.result == 'failure' }}
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BOT_PUSH_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Codex Agent dependencies
        run: pip install openai gitpython requests pytest

      - name: Run Codex Fix Agent
        run: python scripts/codex_fix_and_push.py
